### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by liujiemnm** [sharan21/disentangled-style-transfer-vae#2]
I try to run your code,but there are some small errors,wish you can answer it,thanks!
No such file or directory: './data/yelp/yelp_w2v_embeddings'
"from sklearn.feature_extraction import stop_words"：The API 'stop_words' does not exit,instead,"from sklearn.feature_extraction import text" is right.

**Comment by sharan21** [comment]
Hey, yes these are small bugs that need to be fixed. I will get to it asap but cannot do it right away. I can tell you how to solve both bugs in the meanwhile if you can do it by yourself

1. "No such file or directory: './data/yelp/yelp_w2v_embeddings'": you can disable -w2v while training for now so that the dataset preprocessor will not train w2v embeddings for yelp. If the problem still persists comment out all lines that trains w2v in yelp.py.
2. You need to download stop_words from nltk. You can do this via CLI and should be googlable.

I will fix this and push the changes.
